"""Write hanime cookies in Netscape format suitable for curl."""
import json
import time
from pathlib import Path

# Cookies captured earlier via jshook from your browser session
HANIME_COOKIES = [
    {
        "domain": ".hanime1.me",
        "httpOnly": False,
        "name": "XSRF-TOKEN",
        "path": "/",
        "value": "eyJpdiI6IkVQeDYrQUs4Vlg0b2dHb2FGNTcrSEE9PSIsInZhbHVlIjoiT1JUaHNoVlNpV1wvR3IzTFR1YTdNNWdDY3ErWW1XelNobTNCdlJzMVhMdE00ZktuYkpKaGZlVzB3dzU3VTlZSDEiLCJtYWMiOiJlOGZhZjJhZjg5NDg4ODNkYWE3NDg5YjIxMTM5ODQ2MDkwNzA2NWZkY2E2YmQyZDNlOTkxZjUxMTZhNzkzMDU5In0%3D",
    },
    {
        "domain": ".hanime1.me",
        "httpOnly": True,
        "name": "cf_clearance",
        "path": "/",
        "secure": True,
        "value": "cdbhOG5VNjnIYtCIoAgOMomf_ua1242ZHVCUjOSLeLo-1780884067-1.2.1.1-Ywa23.psb3BWB0Gyx1KLVc0zNl_45xNy3ZxBsQdieF966ivSkwt5zYacBsYeO82XomelmjCuxp7svkAlc8yfj9k1hi_KMgE3KCgxnxhEIhi3fiOtf4SBw8mY4bfhFmu1fgbefDXd7kgAG.I1ghUK5wW9kVc012rG0jI3RECgxFT.Ok9vtVX0iXe5Ntp.r1lloT8.miQYDyi86J0W1cn6aZ_jjVTckwYxAtIRjedVwFcnY1RAHuHNZQRQ1s3r5DDxvBQmvnrlvu5JDW4Kq25qbabL_oNC2jfO4eeGGfpin_3FSv1RJR14Peq8M6IF9yZH5gkC4yjQfFAdbpnTSfksjA",
    },
    {
        "domain": ".hanime1.me",
        "httpOnly": True,
        "name": "remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d",
        "path": "/",
        "value": "eyJpdiI6IldSemxIckkxNFhXQkF6cVFQVVJ2Mnc9PSIsInZhbHVlIjoiUHFoN0tURjJZblBLVlVsaFwveFRtQ0hkK1R6M1k1Y1BIdnhOajRySm9jWGltSnNzWWI5YU9iWnRcL0Z1TEpZZXU3bkxnckNHU1cydEFIVnU1XC92aDluOElhYlI0cElPRDdxYU04a0ZQaVN1TVF6VXZSWHJlMGpEYUZ1dFlwanI5NldsMEQzUzg0S1ZuaHBzUkNFMUlYMEJkV0xhZlgyQStiZVhHVW5xaUkycVZpSTYyWHkrN1ZpVmdrS01BTWpGd0daIiwibWFjIjoiNWUyZGQ5NDI1ZWU5NjkzMDQ4Njg2MmU4ZGViMTkyYjQ4NmU4ZTI1ZWU3MjYyNDU0OWJjNDQyMDNhYmZiYjdmNSJ9",
    },
    {
        "domain": ".hanime1.me",
        "httpOnly": True,
        "name": "hanime1_session",
        "path": "/",
        "value": "eyJpdiI6IlNoZkRVTEZCdXdDRjVjY3BKTGdQeUE9PSIsInZhbHVlIjoiS1wvK0E2U0NYdWsxajNJMTlCQzd0Sm9oa3RnUVo2elh6aUE4aGN5cU5JU2FXY1BYUnhSa1JGRXdHdERWc1A3RFwvIiwibWFjIjoiMjA4NTc4MjA3YmM5ZTE2MDU5MzlkN2U4OWY3OTE2OTE1MGFkNzRhNmRlYzVhN2IzMTBjNzIwMGU4NmZlYTM1YSJ9",
    },
]

IWARA_COOKIES = [
    {
        "domain": ".iwara.tv",
        "httpOnly": True,
        "name": "cf_clearance",
        "path": "/",
        "secure": True,
        "value": "83LCWPVr1BFsoEX3wHRDHj_xU69N9y8.pHdgtfUQSLA-1780884069-1.2.1.1-QAfzBbwVBH5lKBn6dAlAvlnss.cMG6L52Jv.Mg85iC.2ybE8AKC5Zqoa46laN6xuS4lMa7nr8l1GX9kYwUp1Zr.B.Rmosm2rINdRdx6Qve4ITKbjbnay.zJnjAhsSKZeBmriNZ62Bn4vGLckikV.EW90q3o81.OHhYYVSxqLcXbrmGGM5IGvPebdWUZlzsRx_Kk9xKyyM5jXJx0TqbBvIdyaYdJewQFhQRc.cXWMwRIsihHDruFR0PKnKIdr3flh3i0TVKNF3mNGWW_9gJtqBM..RZNENhqw.VHe9KN3RspErYTJ6TGtOjbYa1gshRv43k3OmJoTZ61QwA9_xacoeg",
    },
]


def write_netscape(cookies: list[dict], path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by jshook — browser cookie export",
        "",
    ]
    now = int(time.time())
    for c in cookies:
        domain = c["domain"]
        flag = "TRUE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = str(now + 365 * 86400)  # ~1 year
        name = c["name"]
        val = c["value"]
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{val}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    out_dir = Path("D:/cumhub/anti-nsfw-yolo/data-collector/cookies")
    write_netscape(HANIME_COOKIES, out_dir / "hanime_cookies.txt")
    write_netscape(IWARA_COOKIES, out_dir / "iwara_cookies.txt")
    print("Done.")
